#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
填充游戏名翻译的脚本
规则：
1. 如果 zh 是英文（无中文字符），en = jp = zh
2. 如果 zh 是中文，查找已知翻译字典
"""

import json
import re

# 已知的游戏中文名到英文名的映射
KNOWN_TRANSLATIONS = {
    # 知名游戏
    "前线：二战": "Frontline: World War II",
    "深潜都市": "Deep Dive City",
    "赛博拳击": "Cyber Boxing",
    "我和我的血条": "Me and My Health Bar",
    "迷你岛": "Mini Island",
    "异星传奇": "Alien Legend",
    "救命之恩": "Life Saving Grace",
    "百万致命枪械": "Million Deadly Guns",
    "被遗弃的生活": "Abandoned Life",
    "玛拉的夏天": "Mara's Summer",
    "魂之归宿": "Soul's Resting Place",
    "眼镜蛇 凯：空手道小子再续传奇": "Cobra Kai: The Karate Kid Saga Continues",
    "景安区奇案": "Jing'an District Mystery",
    "无眠夜曲": "Sleepless Nocturne",
    "迪姆鲁萨洛克": "Dim Rusalok",
    "月之泪": "Tears of the Moon",
    "炼狱之日": "Day of Purgatory",
    "冬季雪橇": "Winter Sledge",
    "拉尔夫的冒险：阿兹特克之谜": "Ralph's Adventure: Aztec Mystery",
    "砂之国的宫廷锻冶屋": "Court Blacksmith of the Sand Kingdom",
    "罪恶游行": "Sin Parade",
    "堕星之乱": "Fallen Star Chaos",
    "街头清洁工": "Street Cleaner",
    "胖子囚犯模拟器3": "Fat Prisoner Simulator 3",
    "目标：热身": "Target: Warm Up",
    "星矿": "Star Mine",
    "16位足球": "16-Bit Soccer",
    "艾伦的梦想2": "Ellen's Dream 2",
    "红色殖民地": "Red Colony",
    "王国传说2": "Kingdom Tales 2",
    "烈火战马": "Fire Warhorse",
    "无尽航线": "Endless Route",
    "封灵档案": "Spirit Sealing Archives",
    "松鼠镇的杂货店": "Squirrel Town Grocery",
    "培根叛乱": "Bacon Rebellion",
    "汉字数独": "Kanji Sudoku",
    "X空战": "X Air Combat",
    "弗朗西斯卡2": "Francesca 2",
    "冷风": "Cold Wind",
    "百次机会：堡垒": "100 Chances: Fortress",
    "人类最后的岛屿": "Humanity's Last Island",
    "橙子圣诞老人": "Orange Santa",
    "逃生星球17": "Escape Planet 17",
    "失落的大陆": "Lost Continent",
    "远足": "Hiking",
    # 更多已知游戏...
    "艾尔登法环": "Elden Ring",
    "只狼：影逝二度": "Sekiro: Shadows Die Twice",
    "黑神话：悟空": "Black Myth: Wukong",
    "原神": "Genshin Impact",
    "崩坏：星穹铁道": "Honkai: Star Rail",
    "绝区零": "Zenless Zone Zero",
    "鸣潮": "Wuthering Waves",
    "幻兽帕鲁": "Palworld",
    "博德之门3": "Baldur's Gate 3",
    "星空": "Starfield",
    "赛博朋克2077": "Cyberpunk 2077",
    "巫师3：狂猎": "The Witcher 3: Wild Hunt",
    "荒野大镖客：救赎2": "Red Dead Redemption 2",
    "侠盗猎车手5": "Grand Theft Auto V",
    "最终幻想16": "Final Fantasy XVI",
    "最终幻想7重制版": "Final Fantasy VII Remake",
    "王国之泪": "The Legend of Zelda: Tears of the Kingdom",
    "旷野之息": "The Legend of Zelda: Breath of the Wild",
    "生化危机4重制版": "Resident Evil 4 Remake",
    "生化危机8：村庄": "Resident Evil Village",
    "怪物猎人：崛起": "Monster Hunter Rise",
    "怪物猎人：世界": "Monster Hunter: World",
    "死亡搁浅": "Death Stranding",
    "对马岛之魂": "Ghost of Tsushima",
    "战神：诸神黄昏": "God of War Ragnarök",
    "地平线：西之绝境": "Horizon Forbidden West",
    "蜘蛛侠2": "Marvel's Spider-Man 2",
    "最后生还者": "The Last of Us",
    "空洞骑士": "Hollow Knight",
    "哈迪斯": "Hades",
    "蔚蓝": "Celeste",
    "死亡细胞": "Dead Cells",
    "杀戮尖塔": "Slay the Spire",
    "饥荒": "Don't Starve",
    "缺氧": "Oxygen Not Included",
    "环世界": "RimWorld",
    "戴森球计划": "Dyson Sphere Program",
    "异星工厂": "Factorio",
    "文明6": "Civilization VI",
    "群星": "Stellaris",
    "十字军之王3": "Cruserta Kings III",
    "欧陆风云4": "Europa Universalis IV",
    "钢铁雄心4": "Hearts of Iron IV",
    "全面战争：战锤3": "Total War: Warhammer III",
    "骑马与砍杀2": "Mount & Blade II: Bannerlord",
    "暗黑破坏神4": "Diablo IV",
    "流放之路": "Path of Exile",
    "命运2": "Destiny 2",
    "使命召唤": "Call of Duty",
    "战地": "Battlefield",
    "反恐精英2": "Counter-Strike 2",
    "无畏契约": "Valorant",
    "英雄联盟": "League of Legends",
    "永劫无间": "Naraka: Bladepoint",
    "绝地求生": "PUBG: Battlegrounds",
    "艾迪芬奇的记忆": "What Remains of Edith Finch",
    "极乐迪斯科": "Disco Elysium",
    "潜水员戴夫": "Dave the Diver",
    "双人成行": "It Takes Two",
    "糖豆人": "Fall Guys",
    "胡闹厨房": "Overcooked",
    "泰拉瑞亚": "Terraria",
    "我的世界": "Minecraft",
    "星露谷物语": "Stardew Valley",
    "动物森友会": "Animal Crossing",
    "模拟城市": "SimCity",
    "城市：天际线": "Cities: Skylines",
    "过山车之星": "Planet Coaster",
    "监狱建筑师": "Prison Architect",
    "围攻": "Besiege",
    "人类一败涂地": "Human: Fall Flat",
    "掘地求升": "Getting Over It",
    "超级马里奥": "Super Mario",
    "索尼克": "Sonic",
    "街头霸王6": "Street Fighter 6",
    "拳皇": "The King of Fighters",
    "铁拳8": "Tekken 8",
    "真人快打": "Mortal Kombat",
    "任天堂明星大乱斗": "Super Smash Bros.",
    "火焰纹章": "Fire Emblem",
    "异度神剑": "Xenoblade Chronicles",
    "宝可梦": "Pokémon",
    "勇者斗恶龙": "Dragon Quest",
    "女神异闻录5": "Persona 5",
    "尼尔：机械纪元": "NieR: Automata",
    "鬼泣5": "Devil May Cry 5",
    "猎天使魔女": "Bayonetta",
    "合金装备": "Metal Gear Solid",
    "潜龙谍影": "Metal Gear Solid",
    "黑暗之魂": "Dark Souls",
    "血源诅咒": "Bloodborne",
    "仁王": "Nioh",
    "卧龙：苍天陨落": "Wo Long: Fallen Dynasty",
    "装甲核心6": "Armored Core VI",
    "星际争霸": "StarCraft",
    "魔兽世界": "World of Warcraft",
    "暗黑破坏神": "Diablo",
    "守望先锋": "Overwatch",
    "炉石传说": "Hearthstone",
    "风暴英雄": "Heroes of the Storm",
    "刀塔2": "Dota 2",
    "传送门": "Portal",
    "半衰期": "Half-Life",
    "求生之路": "Left 4 Dead",
    "反恐精英": "Counter-Strike",
    "军团要塞": "Team Fortress",
    "上古卷轴": "The Elder Scrolls",
    "辐射": "Fallout",
    "毁灭战士": "DOOM",
    "雷神之锤": "Quake",
    "德军总部": "Wolfenstein",
    "生化奇兵": "BioShock",
    "羞辱": "Dishonored",
    "掠食": "Prey",
    "死亡循环": "Deathloop",
    "极品飞车": "Need for Speed",
    "地平线": "Forza Horizon",
    "尘埃拉力赛": "DiRT Rally",
    "F1": "F1",
    "实况足球": "eFootball",
    "FIFA足球": "FIFA",
    "NBA 2K": "NBA 2K",
    "WWE 2K": "WWE 2K",
    "刺客信条": "Assassin's Creed",
    "孤岛惊魂": "Far Cry",
    "看门狗": "Watch Dogs",
    "幽灵行动": "Ghost Recon",
    "彩虹六号": "Rainbow Six",
    "全境封锁": "The Division",
    "飙酷车神": "The Crew",
    "纪元": "Anno",
    "工人物语": "The Settlers",
    "魔法门": "Might & Magic",
    "英雄无敌": "Heroes of Might and Magic",
    "波斯王子": "Prince of Persia",
    "雷曼": "Rayman",
    "疯狂兔子": "Rabbids",
    "舞力全开": "Just Dance",
    "古墓丽影": "Tomb Raider",
    "杀手": "Hitman",
    "杀出重围": "Deus Ex",
    "神偷": "Thief",
    "正当防卫": "Just Cause",
    "生活大冒险": "Life is Strange",
    "漫威银河护卫队": "Marvel's Guardians of the Galaxy",
    "漫威复仇者联盟": "Marvel's Avengers",
    "蝙蝠侠阿卡姆": "Batman: Arkham",
    "中土世界": "Middle-earth",
    "霍格沃茨之遗": "Hogwarts Legacy",
    "乐高": "LEGO",
    "模拟人生": "The Sims",
    "模拟农场": "Farming Simulator",
    "欧洲卡车模拟": "Euro Truck Simulator",
    "微软飞行模拟": "Microsoft Flight Simulator",
    "太空工程师": "Space Engineers",
    "坎巴拉太空计划": "Kerbal Space Program",
    "无人深空": "No Man's Sky",
    "精英危险": "Elite Dangerous",
    "X4：基石": "X4: Foundations",
    "星际公民": "Star Citizen",
    "深岩银河": "Deep Rock Galactic",
    "盗贼之海": "Sea of Thieves",
    "腐蚀": "Rust",
    "方舟：生存进化": "ARK: Survival Evolved",
    "森林": "The Forest",
    "绿色地狱": "Green Hell",
    "漫漫长夜": "The Long Dark",
    "七日杀": "7 Days to Die",
    "僵尸世界大战": "World War Z",
    "消逝的光芒": "Dying Light",
    "生化危机": "Resident Evil",
    "寂静岭": "Silent Hill",
    "逃生": "Outlast",
    "心灵杀手": "Alan Wake",
    "层层恐惧": "Layers of Fear",
    "失忆症": "Amnesia",
    "港诡实录": "Paranormal HK",
    "纸嫁衣": "Paper Bride",
    "烟火": "Firework",
    "隐形守护者": "The Invisible Guardian",
    "太吾绘卷": "The Scroll of Taiwu",
    "了不起的修仙模拟器": "Amazing Cultivation Simulator",
    "鬼谷八荒": "Tale of Immortal",
    "觅长生": "Seeking Immortality",
    "戴森球计划": "Dyson Sphere Program",
    "中国式家长": "Chinese Parents",
    "高考恋爱100天": "Gaokao Love 100 Days",
    "完美的一天": "The Perfect Day",
    "逆转裁判": "Ace Attorney",
    "弹丸论破": "Danganronpa",
    "极限脱出": "Zero Escape",
    "AI：梦境档案": "AI: The Somnium Files",
    "命运石之门": "Steins;Gate",
    "恋爱绮谭": "Love Kitan",
    "校园恋物语": "School Love Story",
    "模拟山羊": "Goat Simulator",
    "模拟外科医生": "Surgeon Simulator",
    "八方旅人": "Octopath Traveler",
    "勇气默示录": "Bravely Default",
    "三角战略": "Triangle Strategy",
    "星之海": "Sea of Stars",
    "传说系列": "Tales of",
    "伊苏": "Ys",
    "轨迹系列": "Trails",
    "猎魔人": "The Witcher",
    "神界原罪": "Divinity: Original Sin",
    "永恒之柱": "Pillars of Eternity",
    "暴君": "Tyranny",
    "废土": "Wasteland",
    "星际拓荒": "Outer Wilds",
    "超阈限空间": "Superliminal",
    "传送门骑士": "Portal Knights",
    "见证者": "The Witness",
    "塔罗斯法则": "The Talos Principle",
    "机械迷城": "Machinarium",
    "植物大战僵尸": "Plants vs. Zombies",
    "宝石迷阵": "Bejeweled",
    "祖玛": "Zuma",
    "愤怒的小鸟": "Angry Birds",
    "割绳子": "Cut the Rope",
    "纪念碑谷": "Monument Valley",
    "阿尔托的冒险": "Alto's Adventure",
    "地狱边境": "Limbo",
    "Inside": "Inside",
    "小小梦魇": "Little Nightmares",
    "茶杯头": "Cuphead",
    "奥日": "Ori",
    "光明旅者": "Hyper Light Drifter",
    "武士零": "Katana ZERO",
    "死亡之门": "Death's Door",
    "图尼克": "Tunic",
    "信使": "The Messenger",
    "铲子骑士": "Shovel Knight",
    "洞穴探险": "Spelunky",
    "以撒的结合": "The Binding of Isaac",
    "挺进地牢": "Enter the Gungeon",
    "核爆RPG": "ATOM RPG",
    "末日准备狂": "Mr. Prepper",
    "这是我的战争": "This War of Mine",
    "冰汽时代": "Frostpunk",
    "归家异途": "Home Behind",
    "60秒": "60 Seconds!",
    "庇护所": "Sheltered",
    "避难所": "Fallout Shelter",
    "部落与弯刀": "Sands of Salzaar",
    "太阳帝国的原罪": "Sins of a Solar Empire",
    "银河文明": "Galactic Civilizations",
    "无尽空间": "Endless Space",
    "无尽传说": "Endless Legend",
    "奇迹时代": "Age of Wonders",
    "全面战争": "Total War",
    "帝国时代": "Age of Empires",
    "国家崛起": "Rise of Nations",
    "要塞": "Stronghold",
    "地下城守护者": "Dungeon Keeper",
    "矮人要塞": "Dwarf Fortress",
    "监狱建筑师": "Prison Architect",
    "双点医院": "Two Point Hospital",
    "主题医院": "Theme Hospital",
    "海岛大亨": "Tropico",
    "工业崛起": "Rise of Industry",
    "铁路大亨": "Railroad Tycoon",
    "运输大亨": "Transport Tycoon",
    "开拓者": "OpenTTD",
    "微型都市": "Mini Metro",
    "迷你高速公路": "Mini Motorways",
    "城市规划师": "City Planner",
    "天际线": "Skylines",
}

def is_mainly_english(text):
    """检查文本是否主要是英文（没有中文字符）"""
    # 检查是否包含中文字符
    chinese_pattern = re.compile(r'[\u4e00-\u9fff]')
    return not chinese_pattern.search(text)

def process_game_trans(input_file, output_file):
    """处理游戏翻译文件"""
    with open(input_file, 'r', encoding='utf-8') as f:
        data = json.load(f)

    stats = {
        'total': len(data),
        'english_zh': 0,
        'known_translation': 0,
        'unknown': 0
    }

    for item in data:
        zh = item.get('zh', '')

        if is_mainly_english(zh):
            # 如果 zh 是英文，en 和 jp 都用 zh
            item['en'] = zh
            item['jp'] = zh
            stats['english_zh'] += 1
        elif zh in KNOWN_TRANSLATIONS:
            # 如果有已知翻译
            en_name = KNOWN_TRANSLATIONS[zh]
            item['en'] = en_name
            item['jp'] = en_name  # 日文也用英文名
            stats['known_translation'] += 1
        else:
            # 未知翻译，保持空或用中文名作为占位
            if not item.get('en'):
                item['en'] = zh  # 暂时用中文名
            if not item.get('jp'):
                item['jp'] = zh  # 暂时用中文名
            stats['unknown'] += 1

    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)

    print(f"处理完成!")
    print(f"总计: {stats['total']} 个游戏")
    print(f"英文名游戏: {stats['english_zh']} 个")
    print(f"已知翻译: {stats['known_translation']} 个")
    print(f"未知翻译(使用中文名): {stats['unknown']} 个")

if __name__ == '__main__':
    input_file = '/opt/project/github/wangqizhi/public/data/game-trans.json'
    output_file = '/opt/project/github/wangqizhi/public/data/game-trans.json'
    process_game_trans(input_file, output_file)
